USE [BLOG]
GO
/****** Object:  Schema [COMMON]    Script Date: 22.03.2022 20:08:31 ******/
CREATE SCHEMA [COMMON]
GO
CREATE SCHEMA [CONTENT_MANAGENT]
GO
CREATE SCHEMA [LT_COMMON]
GO
CREATE SCHEMA [LT_CONTENT_MANAGENT]
GO
